# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-12 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='Pic',
            field=models.ImageField(default='', upload_to='/Documents/CRAWLER/'),
            preserve_default=False,
        ),
    ]
