# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170913_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawler',
            old_name='Name',
            new_name='search',
        ),
    ]
