# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_crawler_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawler',
            name='user',
        ),
    ]
