# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170917_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crawler',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
